CREATE TABLE EPS (
    CodiEPS VARCHAR(10) PRIMARY KEY,
    NombreEPS VARCHAR(255) NOT NULL
);

CREATE TABLE IPS (
    NITIPS VARCHAR(15) PRIMARY KEY,
    NombreIPS VARCHAR(255) NOT NULL
);

CREATE TABLE Ubicacion (
    DANE VARCHAR(10) PRIMARY KEY,
    Departamento VARCHAR(255),
    Municipio VARCHAR(255)
);

CREATE TABLE Giros (
    IDGiro SERIAL PRIMARY KEY,
    DANE VARCHAR(10),
    CodiEPS VARCHAR(10),
    NITIPS VARCHAR(15),
    FormaContratacion VARCHAR(255),
    TotalGiro DECIMAL(20, 2),
    TipoGiro VARCHAR(50),
    Observaciones TEXT,
    FOREIGN KEY (DANE) REFERENCES Ubicacion (DANE),
    FOREIGN KEY (CodiEPS) REFERENCES EPS (CodiEPS),
    FOREIGN KEY (NITIPS) REFERENCES IPS (NITIPS)
);
